"""Demo products for local dev when Cosmos DB is not configured."""
from datetime import datetime

from ..models import Product

DEMO_PRODUCTS: list[Product] = [
    Product(
        id="OPT-SEC",
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
        title="Servicios de Ciberseguridad",
        price=0,
        rating=0,
        review_count=0,
        image="https://placehold.co/400x400/1C4E60/ffffff?text=SEC",
        category="Ciberseguridad",
        in_stock=True,
        description="Protección integral contra amenazas cibernéticas.",
        is_service=True,
    ),
    Product(
        id="OPT-ITSM",
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
        title="Servicios ITSM",
        price=0,
        rating=0,
        review_count=0,
        image="https://placehold.co/400x400/D74A3D/ffffff?text=ITSM",
        category="Gestión IT",
        in_stock=True,
        description="Gestión de servicios de TI para optimizar operaciones.",
        is_service=True,
    ),
    Product(
        id="OPT-IA",
        title="Servicios de Inteligencia Artificial",
        price=0,
        rating=0,
        review_count=0,
        image="https://placehold.co/400x400/F39C12/ffffff?text=IA",
        category="Inteligencia Artificial",
        in_stock=True,
        description="Soluciones de IA para transformar procesos.",
        is_service=True,
    ),
    Product(
        id="OPT-BRE",
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
        title="Boutique de Recursos Especializados",
        price=0,
        rating=0,
        review_count=0,
        image="https://placehold.co/400x400/A15C1D/ffffff?text=BRE",
        category="Talento",
        in_stock=True,
        description="Recursos especializados para proyectos tecnológicos.",
        is_service=True,
    ),
    Product(
        id="OPT-CSP",
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
        title="Servicios CSP (Cloud Solution Provider)",
        price=0,
        rating=0,
        review_count=0,
        image="https://placehold.co/400x400/F29C13/ffffff?text=CSP",
        category="Cloud",
        in_stock=True,
        description=(
            "CSP (Cloud Solution Provider) es nuestro programa de licenciamiento flexible para Azure y Microsoft 365. "
            "Incluye asesoría, consultoría, capacitación y soporte ITIL. "
            "Te ayudamos a optimizar licencias, migrar a la nube y aprovechar el ecosistema Microsoft."
        ),
        is_service=True,
    ),
    Product(
        id="OPT-CD",
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
        title="Cloud and Data",
        price=0,
        rating=0,
        review_count=0,
        image="https://placehold.co/400x400/81312E/ffffff?text=C%26D",
        category="Cloud y Datos",
        in_stock=True,
        description="Infraestructura cloud y gestión de datos.",
        is_service=True,
    ),
    Product(
        id="OPT-ADM",
        title="Servicios Administrados",
        price=0,
        rating=0,
        review_count=0,
        image="https://placehold.co/400x400/3D8C9B/ffffff?text=ADM",
        category="Managed Services",
        in_stock=True,
        description="Gestión proactiva de infraestructura IT.",
        is_service=True,
    ),
    Product(
        id="OPT-SEG",
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
        title="Seguridad Integral basada en Microsoft",
        price=0,
        rating=0,
        review_count=0,
        image="https://placehold.co/400x400/1C4E60/ffffff?text=SEG",
        category="Seguridad",
        in_stock=True,
        description="Estrategia de seguridad integral basada en Microsoft.",
        is_service=True,
    ),
]
